import divisibility_factorizations_commutative_rings_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace divisibility_factorizations_commutative_rings_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end divisibility_factorizations_commutative_rings_theorem_canonical_lane_mathlib
end HautevilleHouse
